name: family
description: Osrah Station Application for family

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  pin_entry_text_field: ^0.1.3
  countdown_flutter: ^0.1.2
  countdown: ^0.1.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  #  firebase
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.2
  firebase_auth:  ^1.0.1
  firebase_storage: ^8.0.0
  firebase_messaging: ^9.0.1

  #  local storage
  shared_preferences: ^2.0.5

  # local notification
  flutter_local_notifications: ^5.0.0

  fluttertoast: ^8.0.3
  image_picker:
  file_picker:
  # multi_image_picker: ^4.8.0
  intl:
  flutter_absolute_path: ^1.0.6
  geolocator:
  cached_network_image: ^2.4.1
  get: ^3.26.0
  flutter_document_picker: ^4.0.1
  uuid: 
  bloc: 
  equatable:
  url_launcher: ^4.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/
    - Assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: URW-DIN-Arabic
      fonts:
        - asset: Assets/Fonts/URW-DIN-Arabic.ttf
    - family: URW-DIN-Arabic-Bold
      fonts:
        - asset: Assets/Fonts/URW-DIN-Arabic-Bold-1.ttf
    - family: Careem
      fonts:
        - asset: Assets/Fonts/CAREEM.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
